spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-red-poetry-aqeofnux-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_FPlhqJ0Gdt3S}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: babyshop@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 7vR3kX9pLm2qW5yZ8cB4nF1sH6tJ0oA3dG7uI4pK9wE2rT5yU8iL1oP3sV6xZ
  expiration: 86400000
  refresh-expiration: 604800000
