spring:
  mail:
    host: localhost
    port: 3025
    username: adminrabishop.online@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
