spring:
  application:
    name: BabyShop

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://localhost:5432/BabyShop_bd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:test_user}
    password: ${MAIL_PASSWORD:test_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  base-url: http://localhost:8081
  upload-dir: uploads/products/

jwt:
  secret: QmFieVNob3BTZWNyZXRLZXkyMDI0Rm9ySldUQXV0aGVudGljYXRpb24h
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8081
