spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-red-poetry-aqeofnux-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_FPlhqJ0Gdt3S}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

jwt:
  secret: ${JWT_SECRET:ZGV2LWJhYnlzaG9wLWxvY2FsLWp3dC1zZWNyZXQtbWluLTMyLWJ5dGVzLWtleQ==}
  expiration: 86400000
  refresh-expiration: 604800000
